CREATE DATABASE [Colours]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Colours', FILENAME = N'/var/opt/mssql/data/Colours.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Colours_log', FILENAME = N'/var/opt/mssql/data/Colours_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Colours] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [Colours] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Colours] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Colours] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Colours] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Colours] SET ARITHABORT OFF 
GO
ALTER DATABASE [Colours] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Colours] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Colours] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Colours] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Colours] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Colours] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Colours] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Colours] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Colours] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Colours] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Colours] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Colours] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Colours] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Colours] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Colours] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Colours] SET  READ_WRITE 
GO
ALTER DATABASE [Colours] SET RECOVERY FULL 
GO
ALTER DATABASE [Colours] SET  MULTI_USER 
GO
ALTER DATABASE [Colours] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Colours] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Colours] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Colours]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Colours]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Colours] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO




USE [Colours]
GO

/****** Object:  Table [dbo].[ColourItems]    Script Date: 28/7/2021 15:37:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ColourItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ColourName] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ColourItems] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO





INSERT INTO [dbo].[ColourItems](  ColourName ) VALUES ('Red')
GO

INSERT INTO [dbo].[ColourItems](  ColourName ) VALUES ('Green')
GO


INSERT INTO [dbo].[ColourItems](  ColourName ) VALUES ('Blue')
GO



